
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DA
{

using System;
    using System.Collections.Generic;
    
public partial class articulo
{

    public int ArticuloId { get; set; }

    public int TipoArticuloId { get; set; }

    public int ModeloId { get; set; }

    public string Codigo { get; set; }

    public string Denominacion { get; set; }

    public decimal Precio { get; set; }

    public int Stock { get; set; }

    public bool IndServicio { get; set; }

    public bool Estado { get; set; }



    public virtual tipoarticulo tipoarticulo { get; set; }

    public virtual modelo modelo { get; set; }

}

}
