
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DA
{

using System;
    using System.Collections.Generic;
    
public partial class atencion
{

    public int AtencionId { get; set; }

    public int PacienteId { get; set; }

    public int MedicoId { get; set; }

    public System.DateTime FechaColegiacion { get; set; }

    public string TituloProfesional { get; set; }

    public string Universidad { get; set; }

    public bool Estado { get; set; }



    public virtual paciente paciente { get; set; }

    public virtual medico medico { get; set; }

}

}
