//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class programacion
    {
        public int ProgramacionId { get; set; }
        public int PersonaId { get; set; }
        public int ConsultorioId { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public bool Estado { get; set; }
        public bool Repite { get; set; }
        public string Lunes { get; set; }
        public string Martes { get; set; }
        public string Miercoles { get; set; }
        public string Jueves { get; set; }
        public string Viernes { get; set; }
        public string Sabado { get; set; }
        public string Domingo { get; set; }
    
        public virtual consultorio consultorio { get; set; }
        public virtual persona persona { get; set; }
    }
}
