
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BE
{

using System;
    using System.Collections.Generic;
    
public partial class atencion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public atencion()
    {

        this.atencionespecialidad = new HashSet<atencionespecialidad>();

        this.examen = new HashSet<examen>();

        this.ordenlab = new HashSet<ordenlab>();

    }


    public int AtencionId { get; set; }

    public Nullable<int> CitaId { get; set; }

    public string Estado { get; set; }

    public int PerPacienteId { get; set; }

    public int PerMedicoId { get; set; }

    public System.DateTime Fecha { get; set; }

    public int EspecialidadId { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public int UsuarioCId { get; set; }

    public Nullable<int> UsuarioMId { get; set; }

    public bool IndPago { get; set; }

    public string Motivo { get; set; }

    public string Diagnostico { get; set; }

    public string Tratamiento { get; set; }



    public virtual cita cita { get; set; }

    public virtual persona persona { get; set; }

    public virtual persona persona1 { get; set; }

    public virtual especialidad especialidad { get; set; }

    public virtual usuario usuario { get; set; }

    public virtual usuario usuario1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<atencionespecialidad> atencionespecialidad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<examen> examen { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ordenlab> ordenlab { get; set; }

}

}
