//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cita()
        {
            this.atencion = new HashSet<atencion>();
        }
    
        public int CitaId { get; set; }
        public int PacienteId { get; set; }
        public int ProgramacionId { get; set; }
        public int ConceptoPagoId { get; set; }
        public string Estado { get; set; }
        public bool IndPago { get; set; }
        public int NumeroAtencion { get; set; }
        public System.TimeSpan HoraProbable { get; set; }
        public System.DateTime FechaAtencion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atencion> atencion { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual programacion programacion { get; set; }
        public virtual conceptopago conceptopago { get; set; }
    }
}
