//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public int CitaId { get; set; }
        public int PacienteId { get; set; }
        public int ProgramacionId { get; set; }
        public int ConceptoPagoId { get; set; }
        public Nullable<bool> Estado { get; set; }
        public int NumeroAtencion { get; set; }
        public System.TimeSpan HoraProbable { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual programacion programacion { get; set; }
        public virtual conceptopago conceptopago { get; set; }
    }
}
