//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public int PacienteId { get; set; }
        public int PersonaId { get; set; }
        public string NumeroHistoria { get; set; }
        public string Alergia { get; set; }
        public string AntecedentePersonal { get; set; }
        public string AntecedenteFamiliar { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
