//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class programacion
    {
        public int ProgramacionId { get; set; }
        public int MedicoId { get; set; }
        public int ConsultorioId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Horario { get; set; }
    
        public virtual consultorio consultorio { get; set; }
        public virtual medico medico { get; set; }
    }
}
