//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class topico
    {
        public int TopicoId { get; set; }
        public int AtencionId { get; set; }
        public int Item { get; set; }
        public string Denominacion { get; set; }
        public string Valor { get; set; }
    
        public virtual atencion atencion { get; set; }
    }
}
